Keyvault Integration

diff --git a/iothub-manager/scripts/env-vars-check b/iothub-manager/scripts/env-vars-check
--- a/iothub-manager/scripts/env-vars-check
+++ b/iothub-manager/scripts/env-vars-check
@@ -1,38 +1,17 @@
 #!/usr/bin/env bash
+# Copyright (c) Microsoft. All rights reserved.
 
-# Before checking all the env vars, detect whether secrets, usually encrypted, are available or not.
-# Secrets are not available when building a pull request, so the script will not check for those.
-detect_secrets() {
-    SECRETS_AVAILABLE="true"
-    if [[ "$TRAVIS_PULL_REQUEST" != "" && "$TRAVIS_PULL_REQUEST" != "false" ]]; then
-        SECRETS_AVAILABLE="false"
-        echo "Warning: secrets and encrypted variables are not available when testing pull requests."
-    fi
-}
-
-detect_secrets
-
-if [[ -z "$PCS_IOTHUB_CONNSTRING" && "$SECRETS_AVAILABLE" = "true" ]]; then
-    echo "Error: the PCS_IOTHUB_CONNSTRING environment variable is not defined."
-    exit -1
+if [[ -z "$PCS_KEYVAULT_NAME" ]]; then
+    echo "Error: the PCS_KEYVAULT_NAME environment variable is not defined."
+    exit 1
 fi
 
-if [[ -z "$PCS_STORAGEADAPTER_WEBSERVICE_URL" ]]; then
-    echo "Error: the PCS_STORAGEADAPTER_WEBSERVICE_URL environment variable is not defined."
-    exit -1
+if [[ -z "$PCS_AAD_APPID" ]]; then
+    echo "Error: the PCS_AAD_APPID environment variable is not defined."
+    exit 1
 fi
 
-if [[ -z "$PCS_AUTH_WEBSERVICE_URL" ]]; then
-    echo "Error: the PCS_AUTH_WEBSERVICE_URL environment variable is not defined."
-    exit -1
-fi
-
-if [[ -z "$PCS_AUTH_ISSUER" ]]; then
-    echo "Error: the PCS_AUTH_ISSUER environment variable is not defined."
-    exit -1
-fi
-
-if [[ -z "$PCS_AUTH_AUDIENCE" ]]; then
-    echo "Error: the PCS_AUTH_AUDIENCE environment variable is not defined."
-    exit -1
+if [[ -z "$PCS_AAD_APPSECRET" ]]; then
+    echo "Error: the PCS_AAD_APPSECRET environment variable is not defined."
+    exit 1
 fi
