Setup ASA reference data storage (#8)
* Add new Setup thread to run briefly at bootstrap, to create CosmosDb db and collection, so that the ASA job can start writing into them. All CosmosDb config is in appsettings.ini.  The code is designed to allow extending to other storage types.
* Refactored threads/agents to stop via a cancellation token. The previous approach was not working.
* Overall upgrade internal dependencies to latest versions

diff --git a/asa-manager/scripts/env-vars-check b/asa-manager/scripts/env-vars-check
--- a/asa-manager/scripts/env-vars-check
+++ b/asa-manager/scripts/env-vars-check
@@ -35,3 +35,8 @@ if [[ -z "PCS_EVENTHUB_CONNSTRING" ]]; then
     echo "Error: the PCS_EVENTHUB_CONNSTRING environment variable is not defined."
     exit 1
 fi
+
+if [[ -z "PCS_TELEMETRY_DOCUMENTDB_CONNSTRING" ]]; then
+    echo "Error: the PCS_TELEMETRY_DOCUMENTDB_CONNSTRING environment variable is not defined."
+    exit 1
+fi
