Device Groups Agent (#3)
* Initial Functionality--Device Groups Agent

Initial functionality of device groups agent. Reads device groups from config, gets devices from iot hub manager, writes mapping to blob storage.

diff --git a/asa-manager/scripts/env-vars-check b/asa-manager/scripts/env-vars-check
--- a/asa-manager/scripts/env-vars-check
+++ b/asa-manager/scripts/env-vars-check
@@ -15,3 +15,23 @@ if [[ -z "PCS_IOTHUBMANAGER_WEBSERVICE_URL" ]]; then
     echo "Error: the PCS_IOTHUBMANAGER_WEBSERVICE_URL environment variable is not defined."
     exit 1
 fi
+
+if [[ -z "PCS_ASA_DATA_AZUREBLOB_ACCOUNT" ]]; then
+    echo "Error: the PCS_ASA_DATA_AZUREBLOB_ACCOUNT environment variable is not defined."
+    exit 1
+fi
+
+if [[ -z "PCS_ASA_DATA_AZUREBLOB_KEY" ]]; then
+    echo "Error: the PCS_ASA_DATA_AZUREBLOB_KEY environment variable is not defined."
+    exit 1
+fi
+
+if [[ -z "PCS_ASA_DATA_AZUREBLOB_ENDPOINT_SUFFIX" ]]; then
+    echo "Error: the PCS_ASA_DATA_AZUREBLOB_ENDPOINT_SUFFIX environment variable is not defined."
+    exit 1
+fi
+
+if [[ -z "PCS_EVENTHUB_CONNSTRING" ]]; then
+    echo "Error: the PCS_EVENTHUB_CONNSTRING environment variable is not defined."
+    exit 1
+fi
