Add change checking to DeviceGroupsAgent (#9)
* Initial Event Hub Work

Initial work to include event hub

* Add change logic to GroupAgent

Add logic to agent to check for changes from event hub and device group definitions

* Add unit tests, error handling

Add initial agent unit tests and better error handling for iot hub failures.

* Add env variables to launch settings

Add needed environment variables to launch settings

* Device Groups Agent (#3)

* Initial Functionality--Device Groups Agent

Initial functionality of device groups agent. Reads device groups from config, gets devices from iot hub manager, writes mapping to blob storage.

* Setup ASA reference data storage (#8)

* Add new Setup thread to run briefly at bootstrap, to create CosmosDb db and collection, so that the ASA job can start writing into them. All CosmosDb config is in appsettings.ini.  The code is designed to allow extending to other storage types.
* Refactored threads/agents to stop via a cancellation token. The previous approach was not working.
* Overall upgrade internal dependencies to latest versions

* Remove GroupsAgent (was renamed)
remove groupsagent file

* Add more tests, clean up code

Add more tests, clean up code, move event hub code to Services, add env variables to docker-compose

* Clean up cancellationtoken

Clean up cancellation token code in Agent.cs

* Remove unnecessary new lines

Remove some unnecessary new lines

* Address comments

Add/move around some config variables (removed DeviceGroupsConfig as it made more sense to include in ServicesConfig). Fix some casing

* SetUp->Setup

casing fix

* Improve EventHubStatus

Make a public {get; set;} instead of methods

diff --git a/asa-manager/scripts/env-vars-check b/asa-manager/scripts/env-vars-check
--- a/asa-manager/scripts/env-vars-check
+++ b/asa-manager/scripts/env-vars-check
@@ -40,3 +40,8 @@ if [[ -z "PCS_TELEMETRY_DOCUMENTDB_CONNSTRING" ]]; then
     echo "Error: the PCS_TELEMETRY_DOCUMENTDB_CONNSTRING environment variable is not defined."
     exit 1
 fi
+
+if [[ -z "PCS_EVENTHUB_NAME" ]]; then
+    echo "Error: the PCS_EVENTHUB_NAME environment variable is not defined."
+    exit 1
+fi
